name: Node.js CI

on: [push]

env:
  DATABASE_TYPE: postgresql
  SKIP_DB_CHECK: 1

jobs:
  build:
    if: github.repository == 'umami-software/umami'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - node-version: 18.18
            db-type: postgresql

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm test
      - run: pnpm build-turbo
