name: Node.js CI

on: [push]

env:
  DATABASE_TYPE: postgresql
  SKIP_DB_CHECK: 1

jobs:
  build:
    if: github.repository == 'umami-software/umami'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
        - node-version: 18.18
          pnpm-version: 10
          db-type: postgresql

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4 # required so that setup-node will work
      with:
        version: ${{ matrix.pnpm-version }}
        run_install: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
      env:
        DATABASE_TYPE: ${{ matrix.db-type }}
    - run: npm install --global pnpm
    - run: pnpm install
    - run: pnpm test
    - run: pnpm build
